apiVersion: v1
kind: Template
labels:
  template: 
  selinon: 1.0.0
metadata:
  name: api-imagestream
  annotations:
    description: Selinon API image stream
    openshift.io/display-name: 'Selinon: API'
    version: 1.0.0
    tags: poc,selinon,api
    template.openshift.io/documentation-url: https://github.com/selinon
    template.openshift.io/long-description: Selinon API image stream definition
    template.openshift.io/provider-display-name: Fridolin Pokorny

objects:
- kind: ImageStream
  apiVersion: v1
  metadata:
    labels:
      app: selinon
    name: api
  spec:
    name: latest
